SELECT
    TENANT_ID,
    APP_ID,
    PARAM_NAME,
    EFFECTIVE_VALUE,
    CATEGORY_CODE,
    VALUE_TYPE,
    IS_SECRET,
    LAST_UPDATED_BY,
    LAST_UPDATED_ON
FROM CFG_PARAM_EFFECTIVE_V
WHERE TENANT_ID = NVL(:P0_TENANT_ID, TENANT_ID)
AND APP_ID = NVL(:APP_ID, APP_ID)
ORDER BY TENANT_ID, APP_ID, PARAM_NAME;
