CREATE TABLE TENANTS (
    TENANT_ID        VARCHAR2(50) PRIMARY KEY,
    TENANT_NAME      VARCHAR2(200) NOT NULL,
    TENANT_DESC      VARCHAR2(500),
    IS_ACTIVE        CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_ON       DATE DEFAULT SYSDATE,
    CREATED_BY       VARCHAR2(100)
);

INSERT INTO TENANTS (TENANT_ID, TENANT_NAME, TENANT_DESC) VALUES
('MY_SAAS', 'My SaaS Platform', 'Primary tenant for testing');

CREATE TABLE LKP_PARAM_SCOPE_TYPE (
    SCOPE_TYPE VARCHAR2(10) PRIMARY KEY,
    DESCRIPTION VARCHAR2(200)
);

INSERT INTO LKP_PARAM_SCOPE_TYPE VALUES ('TENANT', 'Tenant-level configuration');
INSERT INTO LKP_PARAM_SCOPE_TYPE VALUES ('APP', 'Application-level configuration');
INSERT INTO LKP_PARAM_SCOPE_TYPE VALUES ('ROLE', 'Role-based configuration');
INSERT INTO LKP_PARAM_SCOPE_TYPE VALUES ('USER', 'User-level configuration');
INSERT INTO LKP_PARAM_SCOPE_TYPE VALUES ('SESSION', 'Session-level configuration');

CREATE TABLE LKP_PARAM_VALUE_TYPE (
    VALUE_TYPE VARCHAR2(15) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100)
);

INSERT INTO LKP_PARAM_VALUE_TYPE VALUES ('STR', 'String');
INSERT INTO LKP_PARAM_VALUE_TYPE VALUES ('NUM', 'Numeric');
INSERT INTO LKP_PARAM_VALUE_TYPE VALUES ('BOOL', 'Boolean');
INSERT INTO LKP_PARAM_VALUE_TYPE VALUES ('JSON', 'JSON object');

CREATE TABLE LKP_PARAM_CATEGORY (
    CATEGORY_CODE VARCHAR2(50) PRIMARY KEY,
    DESCRIPTION   VARCHAR2(200)
);

INSERT INTO LKP_PARAM_CATEGORY VALUES ('SYS', 'System configuration');
INSERT INTO LKP_PARAM_CATEGORY VALUES ('UI', 'User interface configuration');
INSERT INTO LKP_PARAM_CATEGORY VALUES ('INT', 'Integration settings');
